# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013: false
